services:
  - type: web
    name: ligand-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true

      # Configuración de SQLite
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite

      # Otros drivers
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
